# Fly.io deployment configuration for Sophia Backend
app = "sophia-defi-api"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python -c 'print(\"Sophia Backend Starting...\")'"

[[statics]]
  guest_path = "/app/frontend"
  url_prefix = "/frontend"
