services:
  - type: web
    name: sophia-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 8000
    # Health check endpoint
    healthCheckPath: /health
    # Auto-deploy on git push
    autoDeploy: false  # Set to true after initial manual deploy