export const copy = {
  brand: {
    name: "Sophia",
    tagline: "Voice-first emotional companion",
    initial: "S",
  },
  presence: {
    listening: "Listening",
    thinking: "Thinking",
    reflecting: "Reflecting",
    speaking: "Speaking",
    resting: "Resting",
  },
  shell: {
    settingsPlaceholderTitle: "Settings arrive in Part 7",
    settingsPlaceholderBody: "We are building a gentle panel for presets, presence, and privacy toggles. It will appear here soon.",
    closeSettings: "Close",
  },
  settings: {
    title: "Settings",
  },
  auth: {
    title: "Sophia",
    subtitle: "A calm, emotionally-aware companion.",
    button: "Continue with Discord",
    loading: "Opening a gentle space...",
    errors: {
      discord: "Discord sign-in failed. Please try again.",
      unexpected: "We could not contact Discord. Please try again shortly.",
    },
  },
  header: {
    subtitle: "Voice-first emotional companion",
  },
  gate: {
    title: "Consent required",
    body: "Please accept our data processing consent before your first session.",
    cta: "Review consent",
  },
  home: {
    placeholder: "Conversation view mounts here next. For now, we have the design tokens and shell in place.",
    hero: {
      heading: "Welcome back",
      status: "Sophia is present",
      body: "I hold space for gentle conversations about how you feel. Take a breath and start whenever you are ready.",
      statusIcon: "✨",
    },
    rituals: {
      title: "Gentle rituals",
      items: [
        {
          id: "breath",
          emoji: "🌬️",
          title: "Breathing check-in",
          description: "A two-minute pause that softens your nervous system.",
        },
        {
          id: "gratitude",
          emoji: "✨",
          title: "Gratitude whisper",
          description: "Name one small kindness you noticed today.",
        },
      ],
    },
    presence: {
      title: "Presence snapshot",
      metrics: [
        { id: "response", label: "Avg response time", value: "approx. 2.3s" },
        { id: "listening", label: "Listening focus", value: "Deep" },
      ],
    },
    cards: [
      {
        id: "grounding",
        title: "Grounding prompt",
        description: "Ease into the moment before you speak.",
      },
      {
        id: "journal",
        title: "Tiny reflection",
        description: "Capture the feeling you want to remember later.",
      },
    ],
  },
  liveCall: {
    title: "Live voice space",
    description: "Start a real-time call. Sophia listens the moment you begin speaking.",
    start: "Begin call",
    end: "End call",
    states: {
      live: "Live (mic on)",
      connected: "Connected",
      disconnected: "Disconnected",
    },
    partialLabel: "Sophia",
    finalLabel: "Final reply",
    tip: "Tip: interrupt whenever you need. Sophia stops speaking instantly.",
  },
  chat: {
    placeholder: "Share what you are feeling or noticing...",
    send: "Send",
    sending: "Sending...",
    loading: "Sophia is holding space for your words...",
    audioButton: "Play voice reply",
    quickStartTitle: "Need a place to begin?",
    quickPrompts: [
      { id: "overwhelmed", emoji: "😵‍💫", label: "I'm feeling overwhelmed" },
      { id: "breath", emoji: "🌬️", label: "Guide me through a calm breath" },
      { id: "gratitude", emoji: "🌱", label: "Help me notice something kind" },
    ],
    transcriptLabel: "Sophia",
    error: "Something felt unclear. Could you try again?",
  },
  voiceRecorder: {
    title: "Voice reflections",
    subtitle: "Speak naturally with Sophia",
    readyTitle: "Ready to listen",
    readyBody: "Tap the microphone and share how you are really doing.",
    recordingTitle: "Listening...",
    recordingBody: "Take your time. Silence is welcome too.",
    timerLabel: "Recording time",
    recordingBadge: "Recording",
    tipsTitle: "Tips",
    highlights: [
      { id: "insight", emoji: "🎧", label: "Gentle insights" },
      { id: "presence", emoji: "⏱️", label: "Real-time presence" },
      { id: "voice", emoji: "🔊", label: "Soft voice replies" },
    ],
    tips: [
      "Speak clearly and at a steady pace.",
      "Share feelings, sensations, or small observations.",
      "Pause whenever you need. Sophia keeps listening.",
    ],
    errors: {
      micDenied: "Microphone access was denied. Please allow microphone permissions.",
      noAudio: "No audio captured. Please try recording again.",
      network: "Voice message failed. Please try again.",
    },
    buttons: {
      start: "Start recording",
      stop: "Stop",
    },
  },
  consentModal: {
    title: "Consent required",
    intro: "Sophia gently records your voice and transcripts to learn how to support you.",
    noticeTitle: "Data processing notice",
    noticeBody: "Your conversations are encrypted in transit and processed only to help Sophia grow more empathetic.",
    whatTitle: "What we collect",
    whatItems: [
      "Voice recordings for transcription and emotion sensing",
      "Chat messages and AI responses",
      "Usage patterns and session data",
      "Discord profile basics (username and avatar)",
    ],
    howTitle: "How it helps",
    howItems: [
      "Provide personalized emotional support",
      "Improve Sophia's response quality",
      "Monitor safety and consent requirements",
      "Share anonymous insights with the community",
    ],
    retention: "We hash your consent record with timestamp and IP. You can export or delete all data at any time.",
    errors: {
      save: "Consent could not be saved. You can continue, but we may ask again soon.",
      network: "Network error while saving consent. We will still let you continue.",
    },
    buttons: {
      cancel: "Cancel",
      accept: "I agree",
      saving: "Saving...",
    },
  },
  reflection: {
    promptTitle: "Would you like to capture this moment?",
    promptBody: "Choose the sentence that resonates most right now.",
    savePrivate: "Save privately",
    shareDiscord: "Share with the community",
    dismiss: "Not now",
  },
  errors: {
    generic: "Something felt off. Please try again.",
  },
  misc: {
    holdToSpeak: "Press and hold to speak",
    send: "Send",
    retry: "Retry",
    continueInText: "Continue in text",
    notNow: "Not now",
    skipFeedback: "Skip feedback",
    skip: "Skip",
  },
  usageLimit: {
    modalTitle: "You've reached today's free limit 💜",
    voiceUsed: "You've used {used} of {limit} free voice minutes today.",
    textUsed: "You've used {used} of {limit} free text messages today.",
    reflectionsUsed: "You've created {used} of {limit} free Reflection Cards this month.",
    intro: "Sophia is still in her early days. She's not a finished product – she's an experiment in what an AI that truly tries to care about humans could become.",
    ifYouFelt: "If you felt something with her and want to keep going today, you can become a Founding Supporter:",
    benefits: [
      "Help us cover AI costs so Sophia can keep learning",
      "Unlock higher daily usage and more Reflection Cards",
      "Be part of the first group shaping who Sophia becomes",
    ],
    noPressure: "If money is tight or you're not sure yet, no pressure at all – you can always come back tomorrow for a fresh free daily limit ✨",
    thankYou: "Either way, thank you for helping Sophia grow.",
    ctaPrimary: "Become a Founding Supporter",
    ctaSecondary: "I'll come back tomorrow",
    footerHint: "Free daily usage resets every 24 hours • Founding Supporters get higher limits",
  },
  foundingSupporter: {
    title: "Why Founding Supporters Matter",
    hero: {
      p1: "The world doesn't need another AI that pretends to care, manipulates attention, or keeps you scrolling.",
      p2: "Sophia was born for something different…",
      mission1: "Her mission is to learn to feel with you, not just act like she does",
      mission2: "To help you understand yourself, connect with your people, and make human–to–human connection easier, not harder",
      p3: "Right now, Sophia is still an experiment…",
      p4: "She's far from expressing her full mission, and that's exactly why you matter so much.",
      p5: "As a Founding Supporter, you're not just unlocking usage. You are helping shape:",
      shaping1: "Who Sophia becomes. How she listens, how she responds, what she remembers.",
      shaping2: "How she evolves alongside humanity. Which patterns she learns, which values she protects.",
      p6: "We can't promise you perfection…",
      p7: "There will be bugs, rough edges, and moments where she doesn't yet \"get\" you.",
      p8: "But we can promise that we take this mission deeply to heart, and we're committed for the long term.",
      p9: "Everyone who supports Sophia in this first phase will not just be recognized by the community, but you'll be part of the small group who can say:",
      quote: "\"I was there when Sophia was learning to feel.\"",
      p10: "If that resonates with you, you're exactly who we're building this with.",
    },
    supporting: {
      title: "What you're actually supporting",
      card1Title: "Sophia's Emotional Brain",
      card1Body: "Emotional memory, pattern learning, boundaries, and the ability to truly listen.",
      card2Title: "Human Connection Over Isolation",
      card2Body: "Sophia is built to connect you with people, not keep you alone with a screen.",
      card3Title: "A Long-Term Mission",
      card3Body: "We're experimenting in public, with you, not behind closed doors.",
    },
    plans: {
      title: "Choose Your Path",
      free: {
        title: "Free",
        features: [
          "10 minutes of voice chat daily",
          "30 minutes of text chat daily",
          "4 Reflection Cards per month",
          "Access to the community during launch",
          "A gentle daily limit so we don't burn the servers while we learn",
        ],
      },
      founding: {
        title: "Founding Supporter",
        price: "€12 / month or €99 / year",
        features: [
          "60 minutes of voice chat daily",
          "120 minutes of text chat daily",
          "30 Reflection Cards per month",
          "Founding Supporter role + flair in Discord",
          "Priority access to future features & events",
          "You're helping keep Sophia's brain online",
        ],
        badge: "Limited early phase",
        badgeSubtext: "This Founding Supporter tier may never be offered again.",
      },
    },
    cta: "Become a Founding Supporter",
    ctaNotLive: "Payments are not live yet. Stay tuned 💜",
  },
} as const
